ALTER TABLE inquiries
  ADD COLUMN IF NOT EXISTS attachment_url TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS attachment_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS attachment_size BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS attachment_mime_type TEXT NOT NULL DEFAULT '';
